name: aqua_steward
description: "Un sistema diseñado para el monitoreo del nivel y calidad del agua en tiempo real mediante tecnología IoT, promoviendo una gestión eficiente y responsable del recurso hídrico."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^4.2.0
  firebase_core: ^4.10.0
  firebase_messaging: ^16.2.0 # Notificaciones push de Firebase.
  flutter_local_notifications: ^22.0.0 # Notificaciones locales.
  fl_chart: ^1.1.1 # Gráficos.
  http: ^1.6.0 # HTTP para hacer peticiones.
  intl: ^0.20.2 # Formato de fechas.
  socket_io_client: ^3.1.4 # Socket para conectar en tiempo real con el socket.
  shared_preferences: ^2.5.4 # Persistencia de preferencias del usuario.
  screenshot: ^3.0.0 # Captura de pantalla para colocar el gráfico en el PDF.
  package_info_plus: ^9.0.1 # Obtener información del paquete.
  printing: ^5.14.2 # Visualizar, gestionar PDF.
  permission_handler: ^12.0.1 # Manejo de permisos.
  pdf: ^3.11.3 # Generar PDF.
  provider: ^6.1.5+1 # Manejo de estados.
  url_launcher: ^6.3.2 # Abrir enlaces externos (Email, WA, etc).
  flutter_localizations: # Soporte para idiomas.
    sdk: flutter
  flutter_secure_storage: ^10.3.1 # Persistencia de datos sensibles.
  share_plus: ^12.0.2 # Compartir archivos.
  path_provider: ^2.1.6 # Obtener rutas temporales para guardar archivos.
  google_fonts: ^8.2.0
  internet_connection_checker_plus: ^3.1.1 # Verificar si realmente hay internet.
  connectivity_plus: ^7.3.1
  fluid_progress_indicator: ^1.0.1
  multicast_dns: ^0.3.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  # Habilita la autogeneración de código para internacionalización (i18n).
  generate: true
  assets:
    - assets/images/logo_transparente_AquaSteward.png
    - assets/images/deposit.png

# Ejecutar dart run flutter_launcher_icons para configurar el ícono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_AquaSteward.png"
  adaptive_icon_background: "assets/images/background_AquaSteward.png"
  adaptive_icon_foreground: "assets/images/logo_transparente_AquaSteward.png"
  adaptive_icon_monochrome: "assets/images/logo_transparente_AquaSteward_monochrome.png"

# Ejecutar dart run flutter_native_splash:create para configurar el splash screen de la app
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  color_dark: "#010915"
  image: assets/images/logo_transparente_AquaSteward.png
  branding: assets/images/branding.png
  branding_dark: assets/images/branding_dark.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#010915"
    image: assets/images/logo_transparente_AquaSteward.png
    branding: assets/images/branding.png
    branding_dark: assets/images/branding_dark.png